


export const actionTypes = {
    ITEM_FETCH: 'ITEM_FETCH',
    ITEM_POST: 'ITEM_POST',
    ITEM_UPDATE: 'ITEM_UPDATE',
    ITEM_DELETE: 'ITEM_DELETE',
    TYPE_FETCH: 'TYPE_FETCH',
    TYPE_POST: 'TYPE_POST',
    TYPE_UPDATE: 'TYPE_UPDATE',
    TYPE_DELETE: 'TYPE_DELETE',
    SUBTYPE_FETCH: 'SUBTYPE_FETCH',
    SUBTYPE_POST: 'SUBTYPE_POST',
    SUBTYPE_UPDATE: 'SUBTYPE_UPDATE',
    SUBTYPE_DELETE: 'SUBTYPE_DELETE',
    SUBTYPE_DELETEUPDATE: 'SUBTYPE_DELETEUPDATE',
    MESSAGE_CHANGE: 'MESSAGE_CHANGE',
    MESSAGE_CLOSE: 'MESSAGE_CLOSE',
    ITEM_REMOVE_RECENT_ADD: 'ITEM_REMOVE_RECENT_ADD',
    TYPE_REMOVE_RECENT_ADD: 'TYPE_REMOVE_RECENT_ADD',
    S3_POST: 'S3_POST',
    S3_DELETE: 'S3_DELETE',
    S3_DELETEPOST: 'S3_DELETEPOST',
    SEARCH_UDPATE: 'SEARCH_UPDATE',
    INFORMATION_UPDATE: 'INFORMATION_UPDATE',

}
