
export const basePath = 'http://localhost:8080';


export const actionTypes = {
    ITEM_FETCH: 'ITEM_FETCH',
    ITEM_POST: 'ITEM_POST',
    ITEM_UPDATE: 'ITEM_UPDATE',
    ITEM_DELETE: 'ITEM_DELETE',
    TYPE_FETCH: 'TYPE_FETCH',
    TYPE_POST: 'TYPE_POST',
    TYPE_UPDATE: 'TYPE_UPDATE',
    TYPE_DELETE: 'TYPE_DELETE',
    MESSAGE_CHANGE: 'MESSAGE_CHANGE',
    MESSAGE_CLOSE: 'MESSAGE_CLOSE',
    ITEM_REMOVE_RECENT_ADD: 'ITEM_REMOVE_RECENT_ADD'

}
